# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=42)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(to='grumblr.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.CharField(blank=True, default='', max_length=20)),
                ('bio', models.TextField(blank=True, default='', max_length=420)),
                ('email', models.CharField(max_length=200)),
                ('change_pwd', models.CharField(blank=True, default='', max_length=200)),
                ('confirm', models.CharField(blank=True, default='', max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('following', models.ManyToManyField(related_name='_userprofile_following_+', to='grumblr.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
