# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_auto_20161007_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='_userprofile_following_+', to='grumblr.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='change_pwd',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='confirm',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
